global:
  LogLevel: debug

db:
  Path: ./data/db
  Type: badger-db

eth2:
  #  Network:
  #  BeaconNodeAddr: prater-4000-ext.stage.bloxinfra.com:80
  #  BeaconNodeAddr: prater-4000:stage:bloxinfra:com:80
  BeaconNodeAddr: prater-4000-ext.stage.bloxinfra.com:80
ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:
eth1:
  ETH1Addr: ws://eth1-ws-ext.stage.bloxinfra.com/ws
p2p:
  DiscoveryType: mdns
    #  HostAddress: example.ip
  # stage enr
  #  Enr: "enr:-LK4QHVq6HEA2KVnAw593SRMqUOvMGlkP8Jb-qHn4yPLHx--cStvWc38Or2xLcWgDPynVxXPT9NWIEXRzrBUsLmcFkUBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__gmlkgnY0gmlwhDbUHcyJc2VjcDI1NmsxoQO8KQz5L1UEXzEr-CXFFq1th0eG6gopbdul2OQVMuxfMoN0Y3CCE4iDdWRwgg-g"
  TcpPort:
  UdpPort:

bootnode:
  ExternalIP:
  PrivateKey:
